# config/zedx.yaml
# Parameters for Stereolabs ZED X camera
---
/**:
    ros__parameters:
        general:
          camera_model: 'zedx'
          camera_name: 'zed'
          grab_frame_rate: 30
          grab_resolution: 'SVGA'
          camera_timeout: 20
        video:
          exposure_time: 16000
          auto_exposure_time_range_min: 28
          auto_exposure_time_range_max: 30000
          exposure_compensation: 50
          analog_gain: 1255
          auto_analog_gain_range_min: 1000
          auto_analog_gain_range_max: 16000
          digital_gain: 1
          auto_digital_gain_range_min: 1
          auto_digital_gain_range_max: 256
          denoising: 50
          resolution: SVGA
        depth:
          depth_mode: ULTRA
          min_depth: 0.1
          max_depth: 10.0
          confidence_threshold: 5
